### ISSUE TITLE
Не открывается веб-интерфейс после получения токена 

### ISSUE THREAD

**Issue by dronix27** [Moleus/domru#10]
Запускаю аддон первый раз. Получаю токен. Перезапускаю. Аддон запускается, но веб-страница не открывается: Ошибка 502: Bad Gateway. 
Фрагмент журнала:
2024/05/13 04:38:04 http: panic serving 172.30.32.2:34690: runtime error: index out of range [0] with length 0
goroutine 41 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0x853b80?, 0xc0000cc198?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/ad/domru/handlers.(*Handler).HANetwork(0x847640?)
	/go/src/app/handlers/api.go:75 +0x850
github.com/ad/domru/handlers.(*Handler).HomeHandler(0xc0000b04c0, {0x932958, 0xc0001bc000}, 0xc0000ced80)

**Comment by moleus** [comment]
судя по логу ошибка в этой строчке:
https://github.com/moleus/domru/blob/7d545a713fc701d259b97f87a8a0b3235f6195e9/handlers/api.go#L75
и если Interface - это не пустой массив, то, скорее всего, Address.

Вот дока по ендпоинтам супервизора с примером ответа от сервера
https://developers.home-assistant.io/docs/api/supervisor/endpoints#network

Я использую domru в докере и не использую supervisor для HA, поэтому воспроизвести не смогу. Если есть идеи как починить - буду рад PR. Можете предоставить дамп ответа от сервера/добавить нужные логи, тогда будет проще понять в чем дело

**Comment by dronix27** [comment]
> Я использую domru в докере

С докером тоже не особо получилось. Через compose пришлось изменить путь, иначе не могло скопировать. Затем получилось на главную страницу со скриншотом камеры и прочей информацией по аккаунту. Но ссылка на поток не открывается. localhost меняю на свой IP.

**Comment by dronix27** [comment]
Проверил на виртуалке - всё работает. Значит, дело не аддоне.
