### ISSUE TITLE
ARMv7 support

### ISSUE THREAD

**Issue by Mrboob58** [Moleus/domru#20]
Please add ARMv7 support

**Comment by moleus** [comment]
I'm sure you can do it. Here is the [list of architectures](https://github.com/moleus/domru/blob/42c6005c5bcd652073e5fe205482d78be9234190/.goreleaser.yml#L5-L12), just add one and open a PR

**Comment by moleus** [comment]
Here you are: 

https://hub.docker.com/layers/moleus/domru/devel-feat-push-dockerhub/images/sha256-cb22a74c69ad8f747cc0d0964504cbb88441b11ad40751f240de4b09fb8621b0?context=repo
